
---
- name: Deploy to Tomcat
  hosts: web
  become: no
  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "/var/lib/jenkins/workspace/MavenAnsible-CICD/target/MavenAnsibleWebapp.war"
        dest: "/opt/tomcat/webapps/MavenAnsibleWebapp.war"
        remote_src: no
      become: true
    - name:  Restart Tomcat
      systemd:
        name: tomcat
        state: restart
      become: true      

